import 'dotenv/config';

module.exports = [
  {
    name: 'development',
    type: process.env.DEV_TYPE,
    host: process.env.DEV_HOST,
    port: Number(process.env.DEV_HOST),
    username: process.env.DEV_USERNAME,
    password: process.env.DEV_PASSWORD,
    database: process.env.DEV_DATABASE,
    synchronize: true,
    logging: true,
    dropSchema: true,
    entities: ['src/entity/**/*.ts'],
    migrations: ['src/migration/**/*.ts'],
    subscribers: ['src/subscriber/**/*.ts'],
    cli: {
      entitiesDir: 'src/entity',
      migrationsDir: 'src/migration',
      subscribersDir: 'src/subscriber',
    },
    extra: {
      charset: 'utf8mb4_unicode_ci',
    },
  },
  {
    name: 'test',
    type: process.env.TEST_TYPE,
    host: process.env.TEST_HOST,
    port: Number(process.env.TEST_HOST),
    username: process.env.TEST_USERNAME,
    password: process.env.TEST_PASSWORD,
    database: process.env.TEST_DATABASE,
    synchronize: true,
    logging: false,
    dropSchema: true,
    entities: ['src/entity/**/*.ts'],
    migrations: ['src/migration/**/*.ts'],
    subscribers: ['src/subscriber/**/*.ts'],
    cli: {
      entitiesDir: 'src/entity',
      migrationsDir: 'src/migration',
      subscribersDir: 'src/subscriber',
    },
  },
  {
    name: 'production',
    type: process.env.PROD_TYPE,
    host: process.env.PROD_HOST,
    port: Number(process.env.PROD_HOST),
    username: process.env.PROD_USERNAME,
    password: process.env.PROD_PASSWORD,
    database: process.env.PROD_DATABASE,
    synchronize: true,
    logging: false,
    entities: ['src/entity/**/*.ts'],
    migrations: ['src/migration/**/*.ts'],
    subscribers: ['src/subscriber/**/*.ts'],
    cli: {
      entitiesDir: 'src/entity',
      migrationsDir: 'src/migration',
      subscribersDir: 'src/subscriber',
    },
  },
];
