import {
  Provider,
  OpenImageChoice,
  LevelOf3Dae,
  Gender,
  Role,
} from '../../database/entity/User';

const usersInfo = [
  {
    role: Role.USER,
    email: 'jaimebass@calcu.com',
    nickname: 'Robles',
    gender: Gender.MALE,
    provider: Provider.GOOGLE,
    snsId: 'a1',
    openImageChoice: OpenImageChoice.FRIEND,
    levelOf3Dae: LevelOf3Dae.L2,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'roblesbass@calcu.com',
    nickname: 'Petty',
    gender: Gender.FEMALE,
    provider: Provider.GOOGLE,
    snsId: 'a2',
    openImageChoice: OpenImageChoice.CLOSE,
    levelOf3Dae: LevelOf3Dae.L4,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'pettybass@calcu.com',
    nickname: 'Mercedes',
    gender: Gender.FEMALE,
    provider: Provider.FACEBOOK,
    snsId: 'a3',
    openImageChoice: OpenImageChoice.OPEN,
    levelOf3Dae: LevelOf3Dae.L4,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'mercedesbass@calcu.com',
    nickname: 'Logan',
    gender: Gender.FEMALE,
    provider: Provider.FACEBOOK,
    snsId: 'a4',
    openImageChoice: OpenImageChoice.OPEN,
    levelOf3Dae: LevelOf3Dae.L1,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'loganbass@calcu.com',
    nickname: 'Kris',
    gender: Gender.MALE,
    provider: Provider.FACEBOOK,
    snsId: 'a5',
    openImageChoice: OpenImageChoice.CLOSE,
    levelOf3Dae: LevelOf3Dae.L5,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'krisbass@calcu.com',
    nickname: 'Head',
    gender: Gender.MALE,
    provider: Provider.GOOGLE,
    snsId: 'a6',
    openImageChoice: OpenImageChoice.CLOSE,
    levelOf3Dae: LevelOf3Dae.L4,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'headbass@calcu.com',
    nickname: 'Sheppard',
    gender: Gender.FEMALE,
    provider: Provider.GOOGLE,
    snsId: 'a7',
    openImageChoice: OpenImageChoice.OPEN,
    levelOf3Dae: LevelOf3Dae.L2,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'sheppardbass@calcu.com',
    nickname: 'Whitley',
    gender: Gender.FEMALE,
    provider: Provider.GOOGLE,
    snsId: 'a8',
    openImageChoice: OpenImageChoice.FRIEND,
    levelOf3Dae: LevelOf3Dae.L2,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'whitleybass@calcu.com',
    nickname: 'Juliette',
    gender: Gender.MALE,
    provider: Provider.GOOGLE,
    snsId: 'a9',
    openImageChoice: OpenImageChoice.FRIEND,
    levelOf3Dae: LevelOf3Dae.L2,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'juliettebass@calcu.com',
    nickname: 'Wooten',
    gender: Gender.FEMALE,
    provider: Provider.GOOGLE,
    snsId: 'a10',
    openImageChoice: OpenImageChoice.OPEN,
    levelOf3Dae: LevelOf3Dae.L2,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'wootenbass@calcu.com',
    nickname: 'Alford',
    gender: Gender.MALE,
    provider: Provider.GOOGLE,
    snsId: 'a11',
    openImageChoice: OpenImageChoice.CLOSE,
    levelOf3Dae: LevelOf3Dae.L4,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'alfordbass@calcu.com',
    nickname: 'Byrd',
    gender: Gender.FEMALE,
    provider: Provider.GOOGLE,
    snsId: 'a12',
    openImageChoice: OpenImageChoice.CLOSE,
    levelOf3Dae: LevelOf3Dae.L2,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'byrdbass@calcu.com',
    nickname: 'Eloise',
    gender: Gender.FEMALE,
    provider: Provider.FACEBOOK,
    snsId: 'a13',
    openImageChoice: OpenImageChoice.FRIEND,
    levelOf3Dae: LevelOf3Dae.L3,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'eloisebass@calcu.com',
    nickname: 'Shields',
    gender: Gender.MALE,
    provider: Provider.FACEBOOK,
    snsId: 'a14',
    openImageChoice: OpenImageChoice.FRIEND,
    levelOf3Dae: LevelOf3Dae.L3,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'shieldsbass@calcu.com',
    nickname: 'Graham',
    gender: Gender.MALE,
    provider: Provider.GOOGLE,
    snsId: 'a15',
    openImageChoice: OpenImageChoice.OPEN,
    levelOf3Dae: LevelOf3Dae.L1,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'grahambass@calcu.com',
    nickname: 'Mueller',
    gender: Gender.MALE,
    provider: Provider.FACEBOOK,
    snsId: 'a16',
    openImageChoice: OpenImageChoice.OPEN,
    levelOf3Dae: LevelOf3Dae.L3,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'muellerbass@calcu.com',
    nickname: 'Rhonda',
    gender: Gender.MALE,
    provider: Provider.FACEBOOK,
    snsId: 'a17',
    openImageChoice: OpenImageChoice.CLOSE,
    levelOf3Dae: LevelOf3Dae.L2,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'rhondabass@calcu.com',
    nickname: 'Levy',
    gender: Gender.MALE,
    provider: Provider.FACEBOOK,
    snsId: 'a18',
    openImageChoice: OpenImageChoice.FRIEND,
    levelOf3Dae: LevelOf3Dae.L4,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'levybass@calcu.com',
    nickname: 'Francis',
    gender: Gender.FEMALE,
    provider: Provider.GOOGLE,
    snsId: 'a19',
    openImageChoice: OpenImageChoice.FRIEND,
    levelOf3Dae: LevelOf3Dae.L1,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'francisbass@calcu.com',
    nickname: 'Burt',
    gender: Gender.MALE,
    provider: Provider.GOOGLE,
    snsId: 'a20',
    openImageChoice: OpenImageChoice.OPEN,
    levelOf3Dae: LevelOf3Dae.L2,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'burtbass@calcu.com',
    nickname: 'Lana',
    gender: Gender.FEMALE,
    provider: Provider.GOOGLE,
    snsId: 'a21',
    openImageChoice: OpenImageChoice.CLOSE,
    levelOf3Dae: LevelOf3Dae.L3,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'lanabass@calcu.com',
    nickname: 'Ida',
    gender: Gender.MALE,
    provider: Provider.GOOGLE,
    snsId: 'a22',
    openImageChoice: OpenImageChoice.FRIEND,
    levelOf3Dae: LevelOf3Dae.L1,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'idabass@calcu.com',
    nickname: 'Margo',
    gender: Gender.FEMALE,
    provider: Provider.FACEBOOK,
    snsId: 'a23',
    openImageChoice: OpenImageChoice.OPEN,
    levelOf3Dae: LevelOf3Dae.L2,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'margobass@calcu.com',
    nickname: 'Esperanza',
    gender: Gender.FEMALE,
    provider: Provider.FACEBOOK,
    snsId: 'a24',
    openImageChoice: OpenImageChoice.OPEN,
    levelOf3Dae: LevelOf3Dae.L2,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'esperanzabass@calcu.com',
    nickname: 'Finley',
    gender: Gender.MALE,
    provider: Provider.GOOGLE,
    snsId: 'a25',
    openImageChoice: OpenImageChoice.FRIEND,
    levelOf3Dae: LevelOf3Dae.L5,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'finleybass@calcu.com',
    nickname: 'Fran',
    gender: Gender.MALE,
    provider: Provider.FACEBOOK,
    snsId: 'a26',
    openImageChoice: OpenImageChoice.CLOSE,
    levelOf3Dae: LevelOf3Dae.L1,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'franbass@calcu.com',
    nickname: 'Judith',
    gender: Gender.FEMALE,
    provider: Provider.GOOGLE,
    snsId: 'a27',
    openImageChoice: OpenImageChoice.CLOSE,
    levelOf3Dae: LevelOf3Dae.L5,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'judithbass@calcu.com',
    nickname: 'Henson',
    gender: Gender.FEMALE,
    provider: Provider.GOOGLE,
    snsId: 'a28',
    openImageChoice: OpenImageChoice.CLOSE,
    levelOf3Dae: LevelOf3Dae.L4,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'hensonbass@calcu.com',
    nickname: 'Pickett',
    gender: Gender.FEMALE,
    provider: Provider.FACEBOOK,
    snsId: 'a29',
    openImageChoice: OpenImageChoice.OPEN,
    levelOf3Dae: LevelOf3Dae.L5,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'pickettbass@calcu.com',
    nickname: 'Ochoa',
    gender: Gender.MALE,
    provider: Provider.GOOGLE,
    snsId: 'a30',
    openImageChoice: OpenImageChoice.CLOSE,
    levelOf3Dae: LevelOf3Dae.L4,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'ochoabass@calcu.com',
    nickname: 'Emilia',
    gender: Gender.FEMALE,
    provider: Provider.GOOGLE,
    snsId: 'a31',
    openImageChoice: OpenImageChoice.FRIEND,
    levelOf3Dae: LevelOf3Dae.L1,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'emiliabass@calcu.com',
    nickname: 'Enid',
    gender: Gender.FEMALE,
    provider: Provider.GOOGLE,
    snsId: 'a32',
    openImageChoice: OpenImageChoice.CLOSE,
    levelOf3Dae: LevelOf3Dae.L4,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'enidbass@calcu.com',
    nickname: 'Danielle',
    gender: Gender.FEMALE,
    provider: Provider.FACEBOOK,
    snsId: 'a33',
    openImageChoice: OpenImageChoice.CLOSE,
    levelOf3Dae: LevelOf3Dae.L1,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'daniellebass@calcu.com',
    nickname: 'Sanders',
    gender: Gender.MALE,
    provider: Provider.FACEBOOK,
    snsId: 'a34',
    openImageChoice: OpenImageChoice.CLOSE,
    levelOf3Dae: LevelOf3Dae.L5,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'sandersbass@calcu.com',
    nickname: 'Lopez',
    gender: Gender.FEMALE,
    provider: Provider.FACEBOOK,
    snsId: 'a35',
    openImageChoice: OpenImageChoice.OPEN,
    levelOf3Dae: LevelOf3Dae.L3,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'lopezbass@calcu.com',
    nickname: 'Cook',
    gender: Gender.MALE,
    provider: Provider.FACEBOOK,
    snsId: 'a36',
    openImageChoice: OpenImageChoice.CLOSE,
    levelOf3Dae: LevelOf3Dae.L1,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'cookbass@calcu.com',
    nickname: 'Horn',
    gender: Gender.MALE,
    provider: Provider.GOOGLE,
    snsId: 'a37',
    openImageChoice: OpenImageChoice.FRIEND,
    levelOf3Dae: LevelOf3Dae.L5,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'hornbass@calcu.com',
    nickname: 'Salas',
    gender: Gender.MALE,
    provider: Provider.GOOGLE,
    snsId: 'a38',
    openImageChoice: OpenImageChoice.CLOSE,
    levelOf3Dae: LevelOf3Dae.L5,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'salasbass@calcu.com',
    nickname: 'Glenn',
    gender: Gender.MALE,
    provider: Provider.FACEBOOK,
    snsId: 'a39',
    openImageChoice: OpenImageChoice.FRIEND,
    levelOf3Dae: LevelOf3Dae.L3,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'glennbass@calcu.com',
    nickname: 'Flowers',
    gender: Gender.FEMALE,
    provider: Provider.FACEBOOK,
    snsId: 'a40',
    openImageChoice: OpenImageChoice.CLOSE,
    levelOf3Dae: LevelOf3Dae.L5,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'flowersbass@calcu.com',
    nickname: 'Rachelle',
    gender: Gender.FEMALE,
    provider: Provider.GOOGLE,
    snsId: 'a41',
    openImageChoice: OpenImageChoice.FRIEND,
    levelOf3Dae: LevelOf3Dae.L3,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'rachellebass@calcu.com',
    nickname: 'Shauna',
    gender: Gender.FEMALE,
    provider: Provider.FACEBOOK,
    snsId: 'a42',
    openImageChoice: OpenImageChoice.FRIEND,
    levelOf3Dae: LevelOf3Dae.L2,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'shaunabass@calcu.com',
    nickname: 'Ava',
    gender: Gender.MALE,
    provider: Provider.GOOGLE,
    snsId: 'a43',
    openImageChoice: OpenImageChoice.CLOSE,
    levelOf3Dae: LevelOf3Dae.L3,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'avabass@calcu.com',
    nickname: 'Raymond',
    gender: Gender.FEMALE,
    provider: Provider.GOOGLE,
    snsId: 'a44',
    openImageChoice: OpenImageChoice.CLOSE,
    levelOf3Dae: LevelOf3Dae.L4,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'raymondbass@calcu.com',
    nickname: 'Greer',
    gender: Gender.MALE,
    provider: Provider.FACEBOOK,
    snsId: 'a45',
    openImageChoice: OpenImageChoice.FRIEND,
    levelOf3Dae: LevelOf3Dae.L2,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'greerbass@calcu.com',
    nickname: 'Lorraine',
    gender: Gender.FEMALE,
    provider: Provider.FACEBOOK,
    snsId: 'a46',
    openImageChoice: OpenImageChoice.CLOSE,
    levelOf3Dae: LevelOf3Dae.L5,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'lorrainebass@calcu.com',
    nickname: 'Middleton',
    gender: Gender.MALE,
    provider: Provider.FACEBOOK,
    snsId: 'a47',
    openImageChoice: OpenImageChoice.FRIEND,
    levelOf3Dae: LevelOf3Dae.L5,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'middletonbass@calcu.com',
    nickname: 'Cooley',
    gender: Gender.MALE,
    provider: Provider.GOOGLE,
    snsId: 'a48',
    openImageChoice: OpenImageChoice.FRIEND,
    levelOf3Dae: LevelOf3Dae.L3,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'cooleybass@calcu.com',
    nickname: 'Avery',
    gender: Gender.MALE,
    provider: Provider.FACEBOOK,
    snsId: 'a49',
    openImageChoice: OpenImageChoice.OPEN,
    levelOf3Dae: LevelOf3Dae.L2,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'averybass@calcu.com',
    nickname: 'Brennan',
    gender: Gender.FEMALE,
    provider: Provider.FACEBOOK,
    snsId: 'a50',
    openImageChoice: OpenImageChoice.CLOSE,
    levelOf3Dae: LevelOf3Dae.L4,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'brennanbass@calcu.com',
    nickname: 'Bentley',
    gender: Gender.FEMALE,
    provider: Provider.FACEBOOK,
    snsId: 'a51',
    openImageChoice: OpenImageChoice.CLOSE,
    levelOf3Dae: LevelOf3Dae.L1,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'bentleybass@calcu.com',
    nickname: 'Bright',
    gender: Gender.MALE,
    provider: Provider.GOOGLE,
    snsId: 'a52',
    openImageChoice: OpenImageChoice.CLOSE,
    levelOf3Dae: LevelOf3Dae.L3,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'brightbass@calcu.com',
    nickname: 'Maura',
    gender: Gender.FEMALE,
    provider: Provider.GOOGLE,
    snsId: 'a53',
    openImageChoice: OpenImageChoice.CLOSE,
    levelOf3Dae: LevelOf3Dae.L3,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'maurabass@calcu.com',
    nickname: 'Helene',
    gender: Gender.MALE,
    provider: Provider.FACEBOOK,
    snsId: 'a54',
    openImageChoice: OpenImageChoice.CLOSE,
    levelOf3Dae: LevelOf3Dae.L1,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'helenebass@calcu.com',
    nickname: 'Dodson',
    gender: Gender.MALE,
    provider: Provider.GOOGLE,
    snsId: 'a55',
    openImageChoice: OpenImageChoice.OPEN,
    levelOf3Dae: LevelOf3Dae.L5,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'dodsonbass@calcu.com',
    nickname: 'Lee',
    gender: Gender.MALE,
    provider: Provider.GOOGLE,
    snsId: 'a56',
    openImageChoice: OpenImageChoice.CLOSE,
    levelOf3Dae: LevelOf3Dae.L5,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'leebass@calcu.com',
    nickname: 'Sophia',
    gender: Gender.FEMALE,
    provider: Provider.GOOGLE,
    snsId: 'a57',
    openImageChoice: OpenImageChoice.FRIEND,
    levelOf3Dae: LevelOf3Dae.L2,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'sophiabass@calcu.com',
    nickname: 'Sally',
    gender: Gender.MALE,
    provider: Provider.FACEBOOK,
    snsId: 'a58',
    openImageChoice: OpenImageChoice.FRIEND,
    levelOf3Dae: LevelOf3Dae.L5,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'sallybass@calcu.com',
    nickname: 'Best',
    gender: Gender.MALE,
    provider: Provider.FACEBOOK,
    snsId: 'a59',
    openImageChoice: OpenImageChoice.FRIEND,
    levelOf3Dae: LevelOf3Dae.L3,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'bestbass@calcu.com',
    nickname: 'Dionne',
    gender: Gender.MALE,
    provider: Provider.FACEBOOK,
    snsId: 'a60',
    openImageChoice: OpenImageChoice.FRIEND,
    levelOf3Dae: LevelOf3Dae.L4,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'dionnebass@calcu.com',
    nickname: 'Susana',
    gender: Gender.MALE,
    provider: Provider.FACEBOOK,
    snsId: 'a61',
    openImageChoice: OpenImageChoice.FRIEND,
    levelOf3Dae: LevelOf3Dae.L2,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'susanabass@calcu.com',
    nickname: 'Terra',
    gender: Gender.MALE,
    provider: Provider.GOOGLE,
    snsId: 'a62',
    openImageChoice: OpenImageChoice.FRIEND,
    levelOf3Dae: LevelOf3Dae.L1,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'terrabass@calcu.com',
    nickname: 'Roslyn',
    gender: Gender.FEMALE,
    provider: Provider.GOOGLE,
    snsId: 'a63',
    openImageChoice: OpenImageChoice.OPEN,
    levelOf3Dae: LevelOf3Dae.L5,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'roslynbass@calcu.com',
    nickname: 'Alexander',
    gender: Gender.MALE,
    provider: Provider.GOOGLE,
    snsId: 'a64',
    openImageChoice: OpenImageChoice.OPEN,
    levelOf3Dae: LevelOf3Dae.L4,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'alexanderbass@calcu.com',
    nickname: 'Rivas',
    gender: Gender.FEMALE,
    provider: Provider.GOOGLE,
    snsId: 'a65',
    openImageChoice: OpenImageChoice.CLOSE,
    levelOf3Dae: LevelOf3Dae.L2,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'rivasbass@calcu.com',
    nickname: 'Bradshaw',
    gender: Gender.MALE,
    provider: Provider.GOOGLE,
    snsId: 'a66',
    openImageChoice: OpenImageChoice.CLOSE,
    levelOf3Dae: LevelOf3Dae.L1,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'bradshawbass@calcu.com',
    nickname: 'Kelli',
    gender: Gender.FEMALE,
    provider: Provider.GOOGLE,
    snsId: 'a67',
    openImageChoice: OpenImageChoice.CLOSE,
    levelOf3Dae: LevelOf3Dae.L2,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'kellibass@calcu.com',
    nickname: 'Vasquez',
    gender: Gender.MALE,
    provider: Provider.FACEBOOK,
    snsId: 'a68',
    openImageChoice: OpenImageChoice.OPEN,
    levelOf3Dae: LevelOf3Dae.L3,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'vasquezbass@calcu.com',
    nickname: 'Kelly',
    gender: Gender.FEMALE,
    provider: Provider.FACEBOOK,
    snsId: 'a69',
    openImageChoice: OpenImageChoice.CLOSE,
    levelOf3Dae: LevelOf3Dae.L5,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'kellybass@calcu.com',
    nickname: 'Huffman',
    gender: Gender.FEMALE,
    provider: Provider.FACEBOOK,
    snsId: 'a70',
    openImageChoice: OpenImageChoice.FRIEND,
    levelOf3Dae: LevelOf3Dae.L2,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'huffmanbass@calcu.com',
    nickname: 'Cecelia',
    gender: Gender.FEMALE,
    provider: Provider.GOOGLE,
    snsId: 'a71',
    openImageChoice: OpenImageChoice.CLOSE,
    levelOf3Dae: LevelOf3Dae.L2,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'ceceliabass@calcu.com',
    nickname: 'Irene',
    gender: Gender.FEMALE,
    provider: Provider.FACEBOOK,
    snsId: 'a72',
    openImageChoice: OpenImageChoice.FRIEND,
    levelOf3Dae: LevelOf3Dae.L5,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'irenebass@calcu.com',
    nickname: 'Callie',
    gender: Gender.MALE,
    provider: Provider.GOOGLE,
    snsId: 'a73',
    openImageChoice: OpenImageChoice.FRIEND,
    levelOf3Dae: LevelOf3Dae.L5,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'calliebass@calcu.com',
    nickname: 'Adele',
    gender: Gender.FEMALE,
    provider: Provider.GOOGLE,
    snsId: 'a74',
    openImageChoice: OpenImageChoice.CLOSE,
    levelOf3Dae: LevelOf3Dae.L1,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'adelebass@calcu.com',
    nickname: 'Skinner',
    gender: Gender.FEMALE,
    provider: Provider.FACEBOOK,
    snsId: 'a75',
    openImageChoice: OpenImageChoice.OPEN,
    levelOf3Dae: LevelOf3Dae.L1,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'skinnerbass@calcu.com',
    nickname: 'Queen',
    gender: Gender.MALE,
    provider: Provider.GOOGLE,
    snsId: 'a76',
    openImageChoice: OpenImageChoice.FRIEND,
    levelOf3Dae: LevelOf3Dae.L1,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'queenbass@calcu.com',
    nickname: 'Bauer',
    gender: Gender.FEMALE,
    provider: Provider.FACEBOOK,
    snsId: 'a77',
    openImageChoice: OpenImageChoice.CLOSE,
    levelOf3Dae: LevelOf3Dae.L1,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'bauerbass@calcu.com',
    nickname: 'Madeleine',
    gender: Gender.FEMALE,
    provider: Provider.GOOGLE,
    snsId: 'a78',
    openImageChoice: OpenImageChoice.FRIEND,
    levelOf3Dae: LevelOf3Dae.L1,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'madeleinebass@calcu.com',
    nickname: 'Shaffer',
    gender: Gender.MALE,
    provider: Provider.GOOGLE,
    snsId: 'a79',
    openImageChoice: OpenImageChoice.OPEN,
    levelOf3Dae: LevelOf3Dae.L3,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'shafferbass@calcu.com',
    nickname: 'Hazel',
    gender: Gender.FEMALE,
    provider: Provider.GOOGLE,
    snsId: 'a80',
    openImageChoice: OpenImageChoice.FRIEND,
    levelOf3Dae: LevelOf3Dae.L1,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'hazelbass@calcu.com',
    nickname: 'Nola',
    gender: Gender.FEMALE,
    provider: Provider.GOOGLE,
    snsId: 'a81',
    openImageChoice: OpenImageChoice.CLOSE,
    levelOf3Dae: LevelOf3Dae.L2,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'nolabass@calcu.com',
    nickname: 'Parker',
    gender: Gender.MALE,
    provider: Provider.FACEBOOK,
    snsId: 'a82',
    openImageChoice: OpenImageChoice.OPEN,
    levelOf3Dae: LevelOf3Dae.L3,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'parkerbass@calcu.com',
    nickname: 'Beverly',
    gender: Gender.FEMALE,
    provider: Provider.GOOGLE,
    snsId: 'a83',
    openImageChoice: OpenImageChoice.CLOSE,
    levelOf3Dae: LevelOf3Dae.L1,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'beverlybass@calcu.com',
    nickname: 'Hampton',
    gender: Gender.MALE,
    provider: Provider.GOOGLE,
    snsId: 'a84',
    openImageChoice: OpenImageChoice.FRIEND,
    levelOf3Dae: LevelOf3Dae.L3,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'hamptonbass@calcu.com',
    nickname: 'Irma',
    gender: Gender.FEMALE,
    provider: Provider.FACEBOOK,
    snsId: 'a85',
    openImageChoice: OpenImageChoice.FRIEND,
    levelOf3Dae: LevelOf3Dae.L3,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'irmabass@calcu.com',
    nickname: 'Adrienne',
    gender: Gender.MALE,
    provider: Provider.FACEBOOK,
    snsId: 'a86',
    openImageChoice: OpenImageChoice.CLOSE,
    levelOf3Dae: LevelOf3Dae.L1,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'adriennebass@calcu.com',
    nickname: 'Powell',
    gender: Gender.MALE,
    provider: Provider.GOOGLE,
    snsId: 'a87',
    openImageChoice: OpenImageChoice.OPEN,
    levelOf3Dae: LevelOf3Dae.L4,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'powellbass@calcu.com',
    nickname: 'Joanna',
    gender: Gender.MALE,
    provider: Provider.FACEBOOK,
    snsId: 'a88',
    openImageChoice: OpenImageChoice.OPEN,
    levelOf3Dae: LevelOf3Dae.L2,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'joannabass@calcu.com',
    nickname: 'Erma',
    gender: Gender.MALE,
    provider: Provider.FACEBOOK,
    snsId: 'a89',
    openImageChoice: OpenImageChoice.CLOSE,
    levelOf3Dae: LevelOf3Dae.L1,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'ermabass@calcu.com',
    nickname: 'Blanche',
    gender: Gender.FEMALE,
    provider: Provider.GOOGLE,
    snsId: 'a90',
    openImageChoice: OpenImageChoice.OPEN,
    levelOf3Dae: LevelOf3Dae.L1,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'blanchebass@calcu.com',
    nickname: 'Tommie',
    gender: Gender.FEMALE,
    provider: Provider.FACEBOOK,
    snsId: 'a91',
    openImageChoice: OpenImageChoice.FRIEND,
    levelOf3Dae: LevelOf3Dae.L2,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'tommiebass@calcu.com',
    nickname: 'Hubbard',
    gender: Gender.FEMALE,
    provider: Provider.FACEBOOK,
    snsId: 'a92',
    openImageChoice: OpenImageChoice.OPEN,
    levelOf3Dae: LevelOf3Dae.L5,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'hubbardbass@calcu.com',
    nickname: 'Leticia',
    gender: Gender.MALE,
    provider: Provider.FACEBOOK,
    snsId: 'a93',
    openImageChoice: OpenImageChoice.FRIEND,
    levelOf3Dae: LevelOf3Dae.L2,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'leticiabass@calcu.com',
    nickname: 'Reynolds',
    gender: Gender.FEMALE,
    provider: Provider.FACEBOOK,
    snsId: 'a94',
    openImageChoice: OpenImageChoice.FRIEND,
    levelOf3Dae: LevelOf3Dae.L4,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'reynoldsbass@calcu.com',
    nickname: 'Larsen',
    gender: Gender.FEMALE,
    provider: Provider.FACEBOOK,
    snsId: 'a95',
    openImageChoice: OpenImageChoice.CLOSE,
    levelOf3Dae: LevelOf3Dae.L2,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'larsenbass@calcu.com',
    nickname: 'Hardy',
    gender: Gender.FEMALE,
    provider: Provider.GOOGLE,
    snsId: 'a96',
    openImageChoice: OpenImageChoice.CLOSE,
    levelOf3Dae: LevelOf3Dae.L2,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'hardybass@calcu.com',
    nickname: 'Janna',
    gender: Gender.MALE,
    provider: Provider.FACEBOOK,
    snsId: 'a97',
    openImageChoice: OpenImageChoice.FRIEND,
    levelOf3Dae: LevelOf3Dae.L2,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'jannabass@calcu.com',
    nickname: 'Lamb',
    gender: Gender.FEMALE,
    provider: Provider.GOOGLE,
    snsId: 'a98',
    openImageChoice: OpenImageChoice.OPEN,
    levelOf3Dae: LevelOf3Dae.L5,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'lambbass@calcu.com',
    nickname: 'Alice',
    gender: Gender.MALE,
    provider: Provider.FACEBOOK,
    snsId: 'a99',
    openImageChoice: OpenImageChoice.FRIEND,
    levelOf3Dae: LevelOf3Dae.L5,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'alicebass@calcu.com',
    nickname: 'Jerri',
    gender: Gender.FEMALE,
    provider: Provider.FACEBOOK,
    snsId: 'a100',
    openImageChoice: OpenImageChoice.OPEN,
    levelOf3Dae: LevelOf3Dae.L1,
    motivations: [],
    ableDays: [],
    districts: [],
  },
  {
    role: Role.USER,
    email: 'aaa@gmail.com',
    nickname: 'aaa',
    gender: Gender.MALE,
    provider: Provider.GOOGLE,
    snsId: '1',
    openImageChoice: OpenImageChoice.OPEN,
    levelOf3Dae: LevelOf3Dae.L1,
    motivations: [
      'WEIGHT_INCREASE',
      'WEIGHT_LOSS',
      'FIND_FRIEND',
      'LONELINESS',
    ],
    ableDays: [
      'MONDAY',
      'TUESDAY',
      'WEDNESDAY',
      'THURSDAY',
      'FRIDAY',
      'SATURDAY',
      'SUNDAY',
    ],
    districts: [
      { nameOfDong: '대치1동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '대치2동', idOfGu: 1, nameOfGu: '강남구' },
    ],
  },
  {
    role: Role.USER,
    email: 'bbb@gmail.com',
    nickname: 'bbb',
    gender: Gender.MALE,
    provider: Provider.GOOGLE,
    snsId: '2',
    openImageChoice: OpenImageChoice.OPEN,
    levelOf3Dae: LevelOf3Dae.L1,
    motivations: [
      'WEIGHT_INCREASE',
      'WEIGHT_LOSS',
      'FIND_FRIEND',
      'LONELINESS',
    ],
    ableDays: ['MONDAY', 'WEDNESDAY', 'THURSDAY', 'SATURDAY', 'SUNDAY'],
    districts: [
      { nameOfDong: '거여1동', idOfGu: 18, nameOfGu: '송파구' },
      { nameOfDong: '거여2동', idOfGu: 18, nameOfGu: '송파구' },
      { nameOfDong: '마천1동', idOfGu: 18, nameOfGu: '송파구' },
      { nameOfDong: '마천2동', idOfGu: 18, nameOfGu: '송파구' },
    ],
  },
  {
    role: Role.USER,
    email: 'ccc@gmail.com',
    nickname: 'ccc',
    gender: Gender.MALE,
    provider: Provider.GOOGLE,
    snsId: '3',
    openImageChoice: OpenImageChoice.OPEN,
    levelOf3Dae: LevelOf3Dae.L1,
    motivations: [
      'WEIGHT_INCREASE',
      'WEIGHT_LOSS',
      'FIND_FRIEND',
      'LONELINESS',
    ],
    ableDays: [
      'MONDAY',
      'TUESDAY',
      'WEDNESDAY',
      'THURSDAY',
      'FRIDAY',
      'SATURDAY',
      'SUNDAY',
    ],
    districts: [
      { nameOfDong: '거여1동', idOfGu: 18, nameOfGu: '송파구' },
      { nameOfDong: '거여2동', idOfGu: 18, nameOfGu: '송파구' },
      { nameOfDong: '마천1동', idOfGu: 18, nameOfGu: '송파구' },
      { nameOfDong: '마천2동', idOfGu: 18, nameOfGu: '송파구' },
    ],
  },
  {
    role: Role.USER,
    email: 'ddd@gmail.com',
    nickname: 'ddd',
    gender: Gender.MALE,
    provider: Provider.GOOGLE,
    snsId: '4',
    openImageChoice: OpenImageChoice.OPEN,
    levelOf3Dae: LevelOf3Dae.L2,
    motivations: ['WEIGHT_LOSS', 'FIND_FRIEND', 'LONELINESS'],
    ableDays: ['MONDAY', 'WEDNESDAY', 'FRIDAY'],
    districts: [
      { nameOfDong: '거여1동', idOfGu: 18, nameOfGu: '송파구' },
      { nameOfDong: '거여2동', idOfGu: 18, nameOfGu: '송파구' },
      { nameOfDong: '마천1동', idOfGu: 18, nameOfGu: '송파구' },
      { nameOfDong: '마천2동', idOfGu: 18, nameOfGu: '송파구' },
    ],
  },
  {
    role: Role.USER,
    email: 'eee@gmail.com',
    nickname: 'eee',
    gender: Gender.MALE,
    provider: Provider.GOOGLE,
    snsId: '5',
    openImageChoice: OpenImageChoice.OPEN,
    levelOf3Dae: LevelOf3Dae.L2,
    motivations: ['WEIGHT_INCREASE', 'FIND_FRIEND', 'LONELINESS'],
    ableDays: ['MONDAY', 'WEDNESDAY', 'FRIDAY'],
    districts: [
      { nameOfDong: '이태원1동', idOfGu: 21, nameOfGu: '용산구' },
      { nameOfDong: '이태원2동', idOfGu: 21, nameOfGu: '용산구' },
    ],
  },
  {
    role: Role.USER,
    email: 'fff@gmail.com',
    nickname: 'fff',
    gender: Gender.MALE,
    provider: Provider.GOOGLE,
    snsId: '6',
    openImageChoice: OpenImageChoice.FRIEND,
    levelOf3Dae: LevelOf3Dae.L2,
    motivations: ['WEIGHT_INCREASE', 'WEIGHT_LOSS', 'LONELINESS'],
    ableDays: ['MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY'],
    districts: [
      { nameOfDong: '이태원1동', idOfGu: 21, nameOfGu: '용산구' },
      { nameOfDong: '이태원2동', idOfGu: 21, nameOfGu: '용산구' },
    ],
  },
  {
    role: Role.USER,
    email: 'ggg@gmail.com',
    nickname: 'ggg',
    gender: Gender.MALE,
    provider: Provider.GOOGLE,
    snsId: '7',
    openImageChoice: OpenImageChoice.FRIEND,
    levelOf3Dae: LevelOf3Dae.L3,
    motivations: ['WEIGHT_INCREASE', 'WEIGHT_LOSS', 'FIND_FRIEND'],
    ableDays: ['MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY'],
    districts: [
      { nameOfDong: '이태원1동', idOfGu: 21, nameOfGu: '용산구' },
      { nameOfDong: '이태원2동', idOfGu: 21, nameOfGu: '용산구' },
    ],
  },
  {
    role: Role.USER,
    email: 'hhh@gmail.com',
    nickname: 'hhh',
    gender: Gender.MALE,
    provider: Provider.GOOGLE,
    snsId: '8',
    openImageChoice: OpenImageChoice.FRIEND,
    levelOf3Dae: LevelOf3Dae.L3,
    motivations: ['WEIGHT_INCREASE', 'FIND_FRIEND', 'LONELINESS'],
    ableDays: ['MONDAY', 'TUESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY'],
    districts: [
      { nameOfDong: '송파1동', idOfGu: 18, nameOfGu: '송파구' },
      { nameOfDong: '송파2동', idOfGu: 18, nameOfGu: '송파구' },
      { nameOfDong: '잠실4동', idOfGu: 18, nameOfGu: '송파구' },
    ],
  },
  {
    role: Role.USER,
    email: 'iii@gmail.com',
    nickname: 'iii',
    gender: Gender.MALE,
    provider: Provider.GOOGLE,
    snsId: '9',
    openImageChoice: OpenImageChoice.CLOSE,
    levelOf3Dae: LevelOf3Dae.L4,
    motivations: ['WEIGHT_LOSS', 'FIND_FRIEND', 'LONELINESS'],
    ableDays: [
      'MONDAY',
      'WEDNESDAY',
      'THURSDAY',
      'FRIDAY',
      'SATURDAY',
      'SUNDAY',
    ],
    districts: [
      { nameOfDong: '송파1동', idOfGu: 18, nameOfGu: '송파구' },
      { nameOfDong: '송파2동', idOfGu: 18, nameOfGu: '송파구' },
      { nameOfDong: '잠실4동', idOfGu: 18, nameOfGu: '송파구' },
    ],
  },
  {
    role: Role.USER,
    email: 'jjj@gmail.com',
    nickname: 'jjj',
    gender: Gender.MALE,
    provider: Provider.GOOGLE,
    snsId: '10',
    openImageChoice: OpenImageChoice.CLOSE,
    levelOf3Dae: LevelOf3Dae.L4,
    motivations: ['WEIGHT_LOSS', 'FIND_FRIEND', 'LONELINESS'],
    ableDays: [
      'TUESDAY',
      'WEDNESDAY',
      'THURSDAY',
      'FRIDAY',
      'SATURDAY',
      'SUNDAY',
    ],
    districts: [
      { nameOfDong: '대치1동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '대치2동', idOfGu: 1, nameOfGu: '강남구' },
    ],
  },
  {
    role: Role.USER,
    email: 'kkk@gmail.com',
    nickname: 'kkk',
    gender: Gender.MALE,
    provider: Provider.GOOGLE,
    snsId: '11',
    openImageChoice: OpenImageChoice.OPEN,
    levelOf3Dae: LevelOf3Dae.L4,
    motivations: ['WEIGHT_LOSS', 'FIND_FRIEND', 'LONELINESS'],
    ableDays: ['WEDNESDAY', 'THURSDAY', 'SATURDAY'],
    districts: [
      { nameOfDong: '개포1동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '개포2동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '개포4동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '대치1동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '대치2동', idOfGu: 1, nameOfGu: '강남구' },
    ],
  },
  {
    role: Role.USER,
    email: 'lll@gmail.com',
    nickname: 'lll',
    gender: Gender.MALE,
    provider: Provider.GOOGLE,
    snsId: '12',
    openImageChoice: OpenImageChoice.FRIEND,
    levelOf3Dae: LevelOf3Dae.L3,
    motivations: ['WEIGHT_INCREASE', 'WEIGHT_LOSS', 'LONELINESS'],
    ableDays: ['MONDAY', 'WEDNESDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY'],
    districts: [
      { nameOfDong: '일원1동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '일원2동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '일원본동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '대치1동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '대치2동', idOfGu: 1, nameOfGu: '강남구' },
    ],
  },
  {
    role: Role.USER,
    email: 'mmm@gmail.com',
    nickname: 'mmm',
    gender: Gender.MALE,
    provider: Provider.GOOGLE,
    snsId: '13',
    openImageChoice: OpenImageChoice.CLOSE,
    levelOf3Dae: LevelOf3Dae.L2,
    motivations: ['WEIGHT_INCREASE', 'WEIGHT_LOSS', 'FIND_FRIEND'],
    ableDays: ['MONDAY', 'WEDNESDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY'],
    districts: [
      { nameOfDong: '일원1동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '일원2동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '일원본동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '대치1동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '대치2동', idOfGu: 1, nameOfGu: '강남구' },
    ],
  },
  {
    role: Role.USER,
    email: 'nnn@gmail.com',
    nickname: 'nnn',
    gender: Gender.MALE,
    provider: Provider.GOOGLE,
    snsId: '14',
    openImageChoice: OpenImageChoice.OPEN,
    levelOf3Dae: LevelOf3Dae.L1,
    motivations: ['WEIGHT_INCREASE', 'WEIGHT_LOSS', 'LONELINESS'],
    ableDays: ['MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY'],
    districts: [
      { nameOfDong: '일원1동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '일원2동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '일원본동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '대치1동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '대치2동', idOfGu: 1, nameOfGu: '강남구' },
    ],
  },
  {
    role: Role.USER,
    email: 'ooo@gmail.com',
    nickname: 'ooo',
    gender: Gender.MALE,
    provider: Provider.GOOGLE,
    snsId: '15',
    openImageChoice: OpenImageChoice.FRIEND,
    levelOf3Dae: LevelOf3Dae.L4,
    motivations: ['WEIGHT_INCREASE', 'FIND_FRIEND', 'LONELINESS'],
    ableDays: ['MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY'],
    districts: [
      { nameOfDong: '청담동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '대치1동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '대치2동', idOfGu: 1, nameOfGu: '강남구' },
    ],
  },
  {
    role: Role.USER,
    email: 'ppp@gmail.com',
    nickname: 'ppp',
    gender: Gender.MALE,
    provider: Provider.GOOGLE,
    snsId: '16',
    openImageChoice: OpenImageChoice.CLOSE,
    levelOf3Dae: LevelOf3Dae.L3,
    motivations: ['WEIGHT_INCREASE', 'WEIGHT_LOSS'],
    ableDays: ['TUESDAY', 'THURSDAY', 'SATURDAY', 'SUNDAY'],
    districts: [
      { nameOfDong: '청담동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '대치1동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '대치2동', idOfGu: 1, nameOfGu: '강남구' },
    ],
  },
  {
    role: Role.USER,
    email: 'qqq@gmail.com',
    nickname: 'qqq',
    gender: Gender.MALE,
    provider: Provider.GOOGLE,
    snsId: '17',
    openImageChoice: OpenImageChoice.OPEN,
    levelOf3Dae: LevelOf3Dae.L2,
    motivations: ['WEIGHT_LOSS', 'FIND_FRIEND'],
    ableDays: ['TUESDAY', 'THURSDAY', 'SATURDAY', 'SUNDAY'],
    districts: [
      { nameOfDong: '청담동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '대치1동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '대치2동', idOfGu: 1, nameOfGu: '강남구' },
    ],
  },
  {
    role: Role.USER,
    email: 'rrr@gmail.com',
    nickname: 'rrr',
    gender: Gender.MALE,
    provider: Provider.GOOGLE,
    snsId: '18',
    openImageChoice: OpenImageChoice.FRIEND,
    levelOf3Dae: LevelOf3Dae.L1,
    motivations: ['WEIGHT_INCREASE', 'FIND_FRIEND'],
    ableDays: ['MONDAY', 'WEDNESDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY'],
    districts: [
      { nameOfDong: '청담동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '대치1동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '대치2동', idOfGu: 1, nameOfGu: '강남구' },
    ],
  },
  {
    role: Role.USER,
    email: 'sss@gmail.com',
    nickname: 'sss',
    gender: Gender.MALE,
    provider: Provider.GOOGLE,
    snsId: '19',
    openImageChoice: OpenImageChoice.CLOSE,
    levelOf3Dae: LevelOf3Dae.L4,
    motivations: ['FIND_FRIEND', 'LONELINESS'],
    ableDays: ['MONDAY', 'WEDNESDAY', 'FRIDAY'],
    districts: [
      { nameOfDong: '청담동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '개포1동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '개포2동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '개포4동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '대치1동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '대치2동', idOfGu: 1, nameOfGu: '강남구' },
    ],
  },
  {
    role: Role.USER,
    email: 'ttt@gmail.com',
    nickname: 'ttt',
    gender: Gender.FEMALE,
    provider: Provider.GOOGLE,
    snsId: '20',
    openImageChoice: OpenImageChoice.OPEN,
    levelOf3Dae: LevelOf3Dae.L3,
    motivations: ['WEIGHT_INCREASE', 'LONELINESS'],
    ableDays: ['SATURDAY', 'SUNDAY'],
    districts: [
      { nameOfDong: '개포1동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '개포2동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '개포4동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '대치1동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '대치2동', idOfGu: 1, nameOfGu: '강남구' },
    ],
  },
  {
    role: Role.USER,
    email: 'uuu@gmail.com',
    nickname: 'uuu',
    gender: Gender.FEMALE,
    provider: Provider.GOOGLE,
    snsId: '21',
    openImageChoice: OpenImageChoice.FRIEND,
    levelOf3Dae: LevelOf3Dae.L2,
    motivations: ['WEIGHT_INCREASE', 'WEIGHT_LOSS'],
    ableDays: ['SATURDAY', 'SUNDAY'],
    districts: [
      { nameOfDong: '삼성1동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '삼성2동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '대치1동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '대치2동', idOfGu: 1, nameOfGu: '강남구' },
    ],
  },
  {
    role: Role.USER,
    email: 'vvv@gmail.com',
    nickname: 'vvv',
    gender: Gender.FEMALE,
    provider: Provider.GOOGLE,
    snsId: '22',
    openImageChoice: OpenImageChoice.CLOSE,
    levelOf3Dae: LevelOf3Dae.L1,
    motivations: ['WEIGHT_LOSS', 'FIND_FRIEND', 'LONELINESS'],
    ableDays: ['FRIDAY'],
    districts: [
      { nameOfDong: '삼성1동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '삼성2동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '대치1동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '대치2동', idOfGu: 1, nameOfGu: '강남구' },
    ],
  },
  {
    role: Role.USER,
    email: 'www@gmail.com',
    nickname: 'www',
    gender: Gender.FEMALE,
    provider: Provider.GOOGLE,
    snsId: '23',
    openImageChoice: OpenImageChoice.OPEN,
    levelOf3Dae: LevelOf3Dae.L4,
    motivations: ['WEIGHT_INCREASE', 'FIND_FRIEND', 'LONELINESS'],
    ableDays: ['THURSDAY'],
    districts: [
      { nameOfDong: '삼성1동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '삼성2동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '대치1동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '대치2동', idOfGu: 1, nameOfGu: '강남구' },
    ],
  },
  {
    role: Role.USER,
    email: 'xxx@gmail.com',
    nickname: 'xxx',
    gender: Gender.FEMALE,
    provider: Provider.GOOGLE,
    snsId: '24',
    openImageChoice: OpenImageChoice.CLOSE,
    levelOf3Dae: LevelOf3Dae.L3,
    motivations: ['WEIGHT_INCREASE', 'WEIGHT_LOSS', 'LONELINESS'],
    ableDays: ['WEDNESDAY'],
    districts: [
      { nameOfDong: '논현1동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '대치1동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '대치2동', idOfGu: 1, nameOfGu: '강남구' },
    ],
  },
  {
    role: Role.USER,
    email: 'yyy@gmail.com',
    nickname: 'yyy',
    gender: Gender.FEMALE,
    provider: Provider.GOOGLE,
    snsId: '25',
    openImageChoice: OpenImageChoice.FRIEND,
    levelOf3Dae: LevelOf3Dae.L2,
    motivations: ['WEIGHT_INCREASE', 'WEIGHT_LOSS', 'FIND_FRIEND'],
    ableDays: ['TUESDAY'],
    districts: [
      { nameOfDong: '논현1동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '대치1동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '대치2동', idOfGu: 1, nameOfGu: '강남구' },
    ],
  },
  {
    role: Role.USER,
    email: 'zzz@gmail.com',
    nickname: 'zzz',
    gender: Gender.FEMALE,
    provider: Provider.GOOGLE,
    snsId: '26',
    openImageChoice: OpenImageChoice.FRIEND,
    levelOf3Dae: LevelOf3Dae.L1,
    motivations: [
      'WEIGHT_INCREASE',
      'WEIGHT_LOSS',
      'FIND_FRIEND',
      'LONELINESS',
    ],
    ableDays: ['MONDAY'],
    districts: [
      { nameOfDong: '논현1동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '대치1동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '대치2동', idOfGu: 1, nameOfGu: '강남구' },
    ],
  },
  {
    role: Role.USER,
    email: 'bfsudong@gmail.com',
    nickname: 'yg kwon',
    gender: Gender.MALE,
    provider: Provider.GOOGLE,
    snsId: '112259972247432337684',
    openImageChoice: OpenImageChoice.OPEN,
    levelOf3Dae: LevelOf3Dae.L1,
    motivations: [
      'WEIGHT_INCREASE',
      'WEIGHT_LOSS',
      'FIND_FRIEND',
      'LONELINESS',
    ],
    ableDays: [
      'MONDAY',
      'TUESDAY',
      'WEDNESDAY',
      'THURSDAY',
      'FRIDAY',
      'SATURDAY',
      'SUNDAY',
    ],
    districts: [
      { nameOfDong: '대치1동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '대치2동', idOfGu: 1, nameOfGu: '강남구' },
    ],
  },
  {
    role: Role.USER,
    email: 'angelxtry@gmail.com',
    nickname: 'Suho Lee',
    gender: Gender.MALE,
    provider: Provider.GOOGLE,
    snsId: '115844759011217945058',
    openImageChoice: OpenImageChoice.OPEN,
    levelOf3Dae: LevelOf3Dae.L1,
    motivations: [
      'WEIGHT_INCREASE',
      'WEIGHT_LOSS',
      'FIND_FRIEND',
      'LONELINESS',
    ],
    ableDays: [
      'MONDAY',
      'TUESDAY',
      'WEDNESDAY',
      'THURSDAY',
      'FRIDAY',
      'SATURDAY',
      'SUNDAY',
    ],
    districts: [
      { nameOfDong: '대치1동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '대치2동', idOfGu: 1, nameOfGu: '강남구' },
    ],
  },
  {
    role: Role.USER,
    email: 'legendarysuho@gmail.com',
    nickname: 'suho legend',
    gender: Gender.MALE,
    provider: Provider.GOOGLE,
    snsId: '105923364640816320608',
    openImageChoice: OpenImageChoice.OPEN,
    levelOf3Dae: LevelOf3Dae.L1,
    motivations: [
      'WEIGHT_INCREASE',
      'WEIGHT_LOSS',
      'FIND_FRIEND',
      'LONELINESS',
    ],
    ableDays: [
      'MONDAY',
      'TUESDAY',
      'WEDNESDAY',
      'THURSDAY',
      'FRIDAY',
      'SATURDAY',
      'SUNDAY',
    ],
    districts: [
      { nameOfDong: '대치1동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '대치2동', idOfGu: 1, nameOfGu: '강남구' },
    ],
  },
];

export default usersInfo;
