const yongSanGu = [
  { nameOfDong: '방이1동', idOfGu: 3, nameOfGu: '송파구' },
  { nameOfDong: '방이2동', idOfGu: 3, nameOfGu: '송파구' },
  { nameOfDong: '오륜동', idOfGu: 3, nameOfGu: '송파구' },
  { nameOfDong: '풍납1동', idOfGu: 3, nameOfGu: '송파구' },
  { nameOfDong: '풍납2동', idOfGu: 3, nameOfGu: '송파구' },
  { nameOfDong: '송파1동', idOfGu: 3, nameOfGu: '송파구' },
  { nameOfDong: '송파2동', idOfGu: 3, nameOfGu: '송파구' },
  { nameOfDong: '잠실4동', idOfGu: 3, nameOfGu: '송파구' },
  { nameOfDong: '잠실6동', idOfGu: 3, nameOfGu: '송파구' },
  { nameOfDong: '석촌동', idOfGu: 3, nameOfGu: '송파구' },
  { nameOfDong: '삼전동', idOfGu: 3, nameOfGu: '송파구' },
  { nameOfDong: '가락1동', idOfGu: 3, nameOfGu: '송파구' },
  { nameOfDong: '문정2동', idOfGu: 3, nameOfGu: '송파구' },
  { nameOfDong: '잠실본동', idOfGu: 3, nameOfGu: '송파구' },
  { nameOfDong: '잠실2동', idOfGu: 3, nameOfGu: '송파구' },
  { nameOfDong: '잠실3동', idOfGu: 3, nameOfGu: '송파구' },
  { nameOfDong: '잠실7동', idOfGu: 3, nameOfGu: '송파구' },
  { nameOfDong: '거여1동', idOfGu: 3, nameOfGu: '송파구' },
  { nameOfDong: '거여2동', idOfGu: 3, nameOfGu: '송파구' },
  { nameOfDong: '마천1동', idOfGu: 3, nameOfGu: '송파구' },
  { nameOfDong: '마천2동', idOfGu: 3, nameOfGu: '송파구' },
  { nameOfDong: '오금동', idOfGu: 3, nameOfGu: '송파구' },
  { nameOfDong: '가락본동', idOfGu: 3, nameOfGu: '송파구' },
  { nameOfDong: '가락2동', idOfGu: 3, nameOfGu: '송파구' },
  { nameOfDong: '문정1동', idOfGu: 3, nameOfGu: '송파구' },
  { nameOfDong: '장지동', idOfGu: 3, nameOfGu: '송파구' },
  { nameOfDong: '위례동', idOfGu: 3, nameOfGu: '송파구' },
];

export default yongSanGu;
