import { Provider, OpenImageChoice, LevelOf3Dae } from '../entity/User';

const users = [
  {
    email: 'aaa@gmail.com',
    nickname: 'aaa',
    provider: Provider.GOOGLE,
    snsId: '1',
    openImageChoice: OpenImageChoice.OPEN,
    levelOf3Dae: LevelOf3Dae.L1,
    motivations: [
      'WEIGHT_INCREASE',
      'WEIGHT_LOSS',
      'FIND_FRIEND',
      'LONELINESS',
    ],
    ableDays: [
      'MONDAY',
      'TUESDAY',
      'WEDNESDAY',
      'THURSDAY',
      'FRIDAY',
      'SATURDAY',
      'SUNDAY',
    ],
    districts: [
      { nameOfDong: '대치1동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '대치2동', idOfGu: 1, nameOfGu: '강남구' },
    ],
  },
  {
    email: 'bbb@gmail.com',
    nickname: 'bbb',
    provider: Provider.GOOGLE,
    snsId: '2',
    openImageChoice: OpenImageChoice.OPEN,
    levelOf3Dae: LevelOf3Dae.L1,
    motivations: [
      'WEIGHT_INCREASE',
      'WEIGHT_LOSS',
      'FIND_FRIEND',
      'LONELINESS',
    ],
    ableDays: ['MONDAY', 'WEDNESDAY', 'THURSDAY', 'SATURDAY', 'SUNDAY'],
    districts: [
      { nameOfDong: '거여1동', idOfGu: 3, nameOfGu: '송파구' },
      { nameOfDong: '거여2동', idOfGu: 3, nameOfGu: '송파구' },
      { nameOfDong: '마천1동', idOfGu: 3, nameOfGu: '송파구' },
      { nameOfDong: '마천2동', idOfGu: 3, nameOfGu: '송파구' },
    ],
  },
  {
    email: 'ccc@gmail.com',
    nickname: 'ccc',
    provider: Provider.GOOGLE,
    snsId: '3',
    openImageChoice: OpenImageChoice.OPEN,
    levelOf3Dae: LevelOf3Dae.L1,
    motivations: [
      'WEIGHT_INCREASE',
      'WEIGHT_LOSS',
      'FIND_FRIEND',
      'LONELINESS',
    ],
    ableDays: [
      'MONDAY',
      'TUESDAY',
      'WEDNESDAY',
      'THURSDAY',
      'FRIDAY',
      'SATURDAY',
      'SUNDAY',
    ],
    districts: [
      { nameOfDong: '거여1동', idOfGu: 3, nameOfGu: '송파구' },
      { nameOfDong: '거여2동', idOfGu: 3, nameOfGu: '송파구' },
      { nameOfDong: '마천1동', idOfGu: 3, nameOfGu: '송파구' },
      { nameOfDong: '마천2동', idOfGu: 3, nameOfGu: '송파구' },
    ],
  },
  {
    email: 'ddd@gmail.com',
    nickname: 'ddd',
    provider: Provider.GOOGLE,
    snsId: '4',
    openImageChoice: OpenImageChoice.OPEN,
    levelOf3Dae: LevelOf3Dae.L2,
    motivations: ['WEIGHT_LOSS', 'FIND_FRIEND', 'LONELINESS'],
    ableDays: ['MONDAY', 'WEDNESDAY', 'FRIDAY'],
    districts: [
      { nameOfDong: '거여1동', idOfGu: 3, nameOfGu: '송파구' },
      { nameOfDong: '거여2동', idOfGu: 3, nameOfGu: '송파구' },
      { nameOfDong: '마천1동', idOfGu: 3, nameOfGu: '송파구' },
      { nameOfDong: '마천2동', idOfGu: 3, nameOfGu: '송파구' },
    ],
  },
  {
    email: 'eee@gmail.com',
    nickname: 'eee',
    provider: Provider.GOOGLE,
    snsId: '5',
    openImageChoice: OpenImageChoice.OPEN,
    levelOf3Dae: LevelOf3Dae.L2,
    motivations: ['WEIGHT_INCREASE', 'FIND_FRIEND', 'LONELINESS'],
    ableDays: ['MONDAY', 'WEDNESDAY', 'FRIDAY'],
    districts: [
      { nameOfDong: '이태원1동', idOfGu: 2, nameOfGu: '용산구' },
      { nameOfDong: '이태원2동', idOfGu: 2, nameOfGu: '용산구' },
    ],
  },
  {
    email: 'fff@gmail.com',
    nickname: 'fff',
    provider: Provider.GOOGLE,
    snsId: '6',
    openImageChoice: OpenImageChoice.FRIEND,
    levelOf3Dae: LevelOf3Dae.L2,
    motivations: ['WEIGHT_INCREASE', 'WEIGHT_LOSS', 'LONELINESS'],
    ableDays: ['MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY'],
    districts: [
      { nameOfDong: '이태원1동', idOfGu: 2, nameOfGu: '용산구' },
      { nameOfDong: '이태원2동', idOfGu: 2, nameOfGu: '용산구' },
    ],
  },
  {
    email: 'ggg@gmail.com',
    nickname: 'ggg',
    provider: Provider.GOOGLE,
    snsId: '7',
    openImageChoice: OpenImageChoice.FRIEND,
    levelOf3Dae: LevelOf3Dae.L3,
    motivations: ['WEIGHT_INCREASE', 'WEIGHT_LOSS', 'FIND_FRIEND'],
    ableDays: ['MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY'],
    districts: [
      { nameOfDong: '이태원1동', idOfGu: 2, nameOfGu: '용산구' },
      { nameOfDong: '이태원2동', idOfGu: 2, nameOfGu: '용산구' },
    ],
  },
  {
    email: 'hhh@gmail.com',
    nickname: 'hhh',
    provider: Provider.GOOGLE,
    snsId: '8',
    openImageChoice: OpenImageChoice.FRIEND,
    levelOf3Dae: LevelOf3Dae.L3,
    motivations: ['WEIGHT_INCREASE', 'FIND_FRIEND', 'LONELINESS'],
    ableDays: ['MONDAY', 'TUESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY'],
    districts: [
      { nameOfDong: '송파1동', idOfGu: 3, nameOfGu: '송파구' },
      { nameOfDong: '송파2동', idOfGu: 3, nameOfGu: '송파구' },
      { nameOfDong: '잠실4동', idOfGu: 3, nameOfGu: '송파구' },
    ],
  },
  {
    email: 'iii@gmail.com',
    nickname: 'iii',
    provider: Provider.GOOGLE,
    snsId: '9',
    openImageChoice: OpenImageChoice.CLOSE,
    levelOf3Dae: LevelOf3Dae.L4,
    motivations: ['WEIGHT_LOSS', 'FIND_FRIEND', 'LONELINESS'],
    ableDays: [
      'MONDAY',
      'WEDNESDAY',
      'THURSDAY',
      'FRIDAY',
      'SATURDAY',
      'SUNDAY',
    ],
    districts: [
      { nameOfDong: '송파1동', idOfGu: 3, nameOfGu: '송파구' },
      { nameOfDong: '송파2동', idOfGu: 3, nameOfGu: '송파구' },
      { nameOfDong: '잠실4동', idOfGu: 3, nameOfGu: '송파구' },
    ],
  },
  {
    email: 'jjj@gmail.com',
    nickname: 'jjj',
    provider: Provider.GOOGLE,
    snsId: '10',
    openImageChoice: OpenImageChoice.CLOSE,
    levelOf3Dae: LevelOf3Dae.L4,
    motivations: ['WEIGHT_LOSS', 'FIND_FRIEND', 'LONELINESS'],
    ableDays: [
      'TUESDAY',
      'WEDNESDAY',
      'THURSDAY',
      'FRIDAY',
      'SATURDAY',
      'SUNDAY',
    ],
    districts: [
      { nameOfDong: '대치1동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '대치2동', idOfGu: 1, nameOfGu: '강남구' },
    ],
  },
  {
    email: 'kkk@gmail.com',
    nickname: 'kkk',
    provider: Provider.GOOGLE,
    snsId: '11',
    openImageChoice: OpenImageChoice.OPEN,
    levelOf3Dae: LevelOf3Dae.L4,
    motivations: [
      'WEIGHT_LOSS',
      'FIND_FRIEND',
      'LONELINESS',
    ],
    ableDays: [
      'WEDNESDAY',
      'THURSDAY',
      'SATURDAY',
    ],
    districts: [
      { nameOfDong: '개포1동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '개포2동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '개포4동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '대치1동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '대치2동', idOfGu: 1, nameOfGu: '강남구' },
    ],
  },
  {
    email: 'lll@gmail.com',
    nickname: 'lll',
    provider: Provider.GOOGLE,
    snsId: '12',
    openImageChoice: OpenImageChoice.FRIEND,
    levelOf3Dae: LevelOf3Dae.L3,
    motivations: [
      'WEIGHT_INCREASE',
      'WEIGHT_LOSS',
      'LONELINESS',
    ],
    ableDays: [
      'MONDAY',
      'WEDNESDAY',
      'FRIDAY',
      'SATURDAY',
      'SUNDAY',
    ],
    districts: [
      { nameOfDong: '일원1동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '일원2동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '일원본동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '대치1동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '대치2동', idOfGu: 1, nameOfGu: '강남구' },
    ],
  },
  {
    email: 'mmm@gmail.com',
    nickname: 'mmm',
    provider: Provider.GOOGLE,
    snsId: '13',
    openImageChoice: OpenImageChoice.CLOSE,
    levelOf3Dae: LevelOf3Dae.L2,
    motivations: [
      'WEIGHT_INCREASE',
      'WEIGHT_LOSS',
      'FIND_FRIEND',
    ],
    ableDays: [
      'MONDAY',
      'WEDNESDAY',
      'FRIDAY',
      'SATURDAY',
      'SUNDAY',
    ],
    districts: [
      { nameOfDong: '일원1동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '일원2동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '일원본동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '대치1동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '대치2동', idOfGu: 1, nameOfGu: '강남구' },
    ],
  },
  {
    email: 'nnn@gmail.com',
    nickname: 'nnn',
    provider: Provider.GOOGLE,
    snsId: '14',
    openImageChoice: OpenImageChoice.OPEN,
    levelOf3Dae: LevelOf3Dae.L1,
    motivations: [
      'WEIGHT_INCREASE',
      'WEIGHT_LOSS',
      'LONELINESS',
    ],
    ableDays: [
      'MONDAY',
      'TUESDAY',
      'WEDNESDAY',
      'THURSDAY',
      'FRIDAY',
    ],
    districts: [
      { nameOfDong: '일원1동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '일원2동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '일원본동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '대치1동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '대치2동', idOfGu: 1, nameOfGu: '강남구' },
    ],
  },
  {
    email: 'ooo@gmail.com',
    nickname: 'ooo',
    provider: Provider.GOOGLE,
    snsId: '15',
    openImageChoice: OpenImageChoice.FRIEND,
    levelOf3Dae: LevelOf3Dae.L4,
    motivations: [
      'WEIGHT_INCREASE',
      'FIND_FRIEND',
      'LONELINESS',
    ],
    ableDays: [
      'MONDAY',
      'TUESDAY',
      'WEDNESDAY',
      'THURSDAY',
      'FRIDAY',
    ],
    districts: [
      { nameOfDong: '청담동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '대치1동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '대치2동', idOfGu: 1, nameOfGu: '강남구' },
    ],
  },
  {
    email: 'ppp@gmail.com',
    nickname: 'ppp',
    provider: Provider.GOOGLE,
    snsId: '16',
    openImageChoice: OpenImageChoice.CLOSE,
    levelOf3Dae: LevelOf3Dae.L3,
    motivations: [
      'WEIGHT_INCREASE',
      'WEIGHT_LOSS',
    ],
    ableDays: [
      'TUESDAY',
      'THURSDAY',
      'SATURDAY',
      'SUNDAY',
    ],
    districts: [
      { nameOfDong: '청담동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '대치1동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '대치2동', idOfGu: 1, nameOfGu: '강남구' },
    ],
  },
  {
    email: 'qqq@gmail.com',
    nickname: 'qqq',
    provider: Provider.GOOGLE,
    snsId: '17',
    openImageChoice: OpenImageChoice.OPEN,
    levelOf3Dae: LevelOf3Dae.L2,
    motivations: [
      'WEIGHT_LOSS',
      'FIND_FRIEND',
    ],
    ableDays: [
      'TUESDAY',
      'THURSDAY',
      'SATURDAY',
      'SUNDAY',
    ],
    districts: [
      { nameOfDong: '청담동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '대치1동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '대치2동', idOfGu: 1, nameOfGu: '강남구' },
    ],
  },
  {
    email: 'rrr@gmail.com',
    nickname: 'rrr',
    provider: Provider.GOOGLE,
    snsId: '18',
    openImageChoice: OpenImageChoice.FRIEND,
    levelOf3Dae: LevelOf3Dae.L1,
    motivations: [
      'WEIGHT_INCREASE',
      'FIND_FRIEND',
    ],
    ableDays: [
      'MONDAY',
      'WEDNESDAY',
      'FRIDAY',
      'SATURDAY',
      'SUNDAY',
    ],
    districts: [
      { nameOfDong: '청담동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '대치1동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '대치2동', idOfGu: 1, nameOfGu: '강남구' },
    ],
  },
  {
    email: 'sss@gmail.com',
    nickname: 'sss',
    provider: Provider.GOOGLE,
    snsId: '19',
    openImageChoice: OpenImageChoice.CLOSE,
    levelOf3Dae: LevelOf3Dae.L4,
    motivations: [
      'FIND_FRIEND',
      'LONELINESS',
    ],
    ableDays: [
      'MONDAY',
      'WEDNESDAY',
      'FRIDAY',
    ],
    districts: [
      { nameOfDong: '청담동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '개포1동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '개포2동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '개포4동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '대치1동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '대치2동', idOfGu: 1, nameOfGu: '강남구' },
    ],
  },
  {
    email: 'ttt@gmail.com',
    nickname: 'ttt',
    provider: Provider.GOOGLE,
    snsId: '20',
    openImageChoice: OpenImageChoice.OPEN,
    levelOf3Dae: LevelOf3Dae.L3,
    motivations: [
      'WEIGHT_INCREASE',
      'LONELINESS',
    ],
    ableDays: [
      'SATURDAY',
      'SUNDAY',
    ],
    districts: [
      { nameOfDong: '개포1동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '개포2동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '개포4동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '대치1동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '대치2동', idOfGu: 1, nameOfGu: '강남구' },
    ],
  },
  {
    email: 'uuu@gmail.com',
    nickname: 'uuu',
    provider: Provider.GOOGLE,
    snsId: '21',
    openImageChoice: OpenImageChoice.FRIEND,
    levelOf3Dae: LevelOf3Dae.L2,
    motivations: [
      'WEIGHT_INCREASE',
      'WEIGHT_LOSS',
    ],
    ableDays: [
      'SATURDAY',
      'SUNDAY',
    ],
    districts: [
      { nameOfDong: '삼성1동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '삼성2동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '대치1동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '대치2동', idOfGu: 1, nameOfGu: '강남구' },
    ],
  },
  {
    email: 'vvv@gmail.com',
    nickname: 'vvv',
    provider: Provider.GOOGLE,
    snsId: '22',
    openImageChoice: OpenImageChoice.CLOSE,
    levelOf3Dae: LevelOf3Dae.L1,
    motivations: [
      'WEIGHT_LOSS',
      'FIND_FRIEND',
      'LONELINESS',
    ],
    ableDays: [
      'FRIDAY',
    ],
    districts: [
      { nameOfDong: '삼성1동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '삼성2동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '대치1동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '대치2동', idOfGu: 1, nameOfGu: '강남구' },
    ],
  },
  {
    email: 'www@gmail.com',
    nickname: 'www',
    provider: Provider.GOOGLE,
    snsId: '23',
    openImageChoice: OpenImageChoice.OPEN,
    levelOf3Dae: LevelOf3Dae.L4,
    motivations: [
      'WEIGHT_INCREASE',
      'FIND_FRIEND',
      'LONELINESS',
    ],
    ableDays: [
      'THURSDAY',
    ],
    districts: [
      { nameOfDong: '삼성1동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '삼성2동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '대치1동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '대치2동', idOfGu: 1, nameOfGu: '강남구' },
    ],
  },
  {
    email: 'xxx@gmail.com',
    nickname: 'xxx',
    provider: Provider.GOOGLE,
    snsId: '24',
    openImageChoice: OpenImageChoice.CLOSE,
    levelOf3Dae: LevelOf3Dae.L3,
    motivations: [
      'WEIGHT_INCREASE',
      'WEIGHT_LOSS',
      'LONELINESS',
    ],
    ableDays: [
      'WEDNESDAY',
    ],
    districts: [
      { nameOfDong: '논현1동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '대치1동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '대치2동', idOfGu: 1, nameOfGu: '강남구' },
    ],
  },
  {
    email: 'yyy@gmail.com',
    nickname: 'yyy',
    provider: Provider.GOOGLE,
    snsId: '25',
    openImageChoice: OpenImageChoice.FRIEND,
    levelOf3Dae: LevelOf3Dae.L2,
    motivations: [
      'WEIGHT_INCREASE',
      'WEIGHT_LOSS',
      'FIND_FRIEND',
    ],
    ableDays: [
      'TUESDAY',
    ],
    districts: [
      { nameOfDong: '논현1동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '대치1동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '대치2동', idOfGu: 1, nameOfGu: '강남구' },
    ],
  },
  {
    email: 'zzz@gmail.com',
    nickname: 'zzz',
    provider: Provider.GOOGLE,
    snsId: '26',
    openImageChoice: OpenImageChoice.FRIEND,
    levelOf3Dae: LevelOf3Dae.L1,
    motivations: [
      'WEIGHT_INCREASE',
      'WEIGHT_LOSS',
      'FIND_FRIEND',
      'LONELINESS',
    ],
    ableDays: [
      'MONDAY',
    ],
    districts: [
      { nameOfDong: '논현1동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '대치1동', idOfGu: 1, nameOfGu: '강남구' },
      { nameOfDong: '대치2동', idOfGu: 1, nameOfGu: '강남구' },
    ],
  },
];

export default users;
