import { Provider, OpenImageChoice, LevelOf3Dae } from '../entity/User';

const users = [
  {
    id: 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
    email: 'aaa@gmail.com',
    nickname: 'aaa',
    provider: Provider.GOOGLE,
    snsId: '1',
    openImageChoice: OpenImageChoice.OPEN,
    levelOf3Dae: LevelOf3Dae.L1,
  },
  {
    id: 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaab',
    email: 'bbb@gmail.com',
    nickname: 'bbb',
    provider: Provider.GOOGLE,
    snsId: '2',
    openImageChoice: OpenImageChoice.OPEN,
    levelOf3Dae: LevelOf3Dae.L1,
  },
  {
    id: 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaac',
    email: 'ccc@gmail.com',
    nickname: 'ccc',
    provider: Provider.GOOGLE,
    snsId: '3',
    openImageChoice: OpenImageChoice.OPEN,
    levelOf3Dae: LevelOf3Dae.L1,
  },
  {
    id: 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaad',
    email: 'ddd@gmail.com',
    nickname: 'ddd',
    provider: Provider.GOOGLE,
    snsId: '4',
    openImageChoice: OpenImageChoice.OPEN,
    levelOf3Dae: LevelOf3Dae.L2,
  },
  {
    id: 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaae',
    email: 'eee@gmail.com',
    nickname: 'eee',
    provider: Provider.GOOGLE,
    snsId: '5',
    openImageChoice: OpenImageChoice.OPEN,
    levelOf3Dae: LevelOf3Dae.L2,
  },
  {
    id: 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaf',
    email: 'fff@gmail.com',
    nickname: 'fff',
    provider: Provider.GOOGLE,
    snsId: '6',
    openImageChoice: OpenImageChoice.FRIEND,
    levelOf3Dae: LevelOf3Dae.L2,
  },
  {
    id: 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaag',
    email: 'ggg@gmail.com',
    nickname: 'ggg',
    provider: Provider.GOOGLE,
    snsId: '7',
    openImageChoice: OpenImageChoice.FRIEND,
    levelOf3Dae: LevelOf3Dae.L3,
  },
  {
    id: 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaah',
    email: 'hhh@gmail.com',
    nickname: 'hhh',
    provider: Provider.GOOGLE,
    snsId: '8',
    openImageChoice: OpenImageChoice.FRIEND,
    levelOf3Dae: LevelOf3Dae.L3,
  },
  {
    id: 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaai',
    email: 'iii@gmail.com',
    nickname: 'iii',
    provider: Provider.GOOGLE,
    snsId: '9',
    openImageChoice: OpenImageChoice.CLOSE,
    levelOf3Dae: LevelOf3Dae.L4,
  },
  {
    id: 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaj',
    email: 'jjj@gmail.com',
    nickname: 'jjj',
    provider: Provider.GOOGLE,
    snsId: '10',
    openImageChoice: OpenImageChoice.CLOSE,
    levelOf3Dae: LevelOf3Dae.L4,
  },
];

export default users;
